import io

import matplotlib.pyplot as plt
import streamlit as st

# MCEQ
import MCEq.core
import MCEq.particlemanager
import crflux.models as crf


if "last_fig" not in st.session_state:
    st.session_state.last_fig = None

if "last_png" not in st.session_state:
    st.session_state.last_png = None

st.set_page_config(
    page_title="AERIS",
    layout="wide",
)


def run_mceq(
    interaction_model,
    primary_model_name,
    theta_deg,
    mag,
    use_muons,
    use_numu,
    use_nue,
    use_nutau,
    flux_prefixes,
):
    # Map primary model names to the format expected by MCEq
    if primary_model_name == "H3a":
        primary_model = (crf.HillasGaisser2012, "H3a")
    elif primary_model_name == "H4a":
        primary_model = (crf.HillasGaisser2012, "H4a")
    elif primary_model_name == "GST3":
        primary_model = (crf.GaisserStanevTilav, "3-gen")
    elif primary_model_name == "GST4":
        primary_model = (crf.GaisserStanevTilav, "4-gen")
    else:
        primary_model = (crf.HillasGaisser2012, "H3a")

    if len(flux_prefixes) == 0:
        raise ValueError(
            "Please select at least one flux type (Prompt, Conventional, or Total)."
        )

    mceq = MCEq.core.MCEqRun(
        interaction_model=interaction_model,
        primary_model=primary_model,
        theta_deg=theta_deg,
    )

    mceq.solve()
    energies = mceq.e_grid

    flux_name = {
        "pr_": "Prompt",
        "conv_": "Convencional",
        "total_": "Total",
    }

    fig, ax = plt.subplots()
    ax.set_xscale("log")
    ax.set_yscale("log")

    # ---------------- MUONS ----------------
    if use_muons:
        for prefix in flux_prefixes:
            muon_flux = mceq.get_solution(f"{prefix}mu+", mag) + mceq.get_solution(
                f"{prefix}mu-", mag
            )
            ax.plot(
                energies,
                muon_flux,
                label=rf"Fluxo {flux_name.get(prefix, prefix)} $\mu^+, \mu^-$",
            )

    # ---------------- NU MU ----------------
    if use_numu:
        for prefix in flux_prefixes:
            numu_flux = mceq.get_solution(f"{prefix}numu", mag) + mceq.get_solution(
                f"{prefix}antinumu", mag
            )
            ax.plot(
                energies,
                numu_flux,
                label=rf"Fluxo {flux_name.get(prefix, prefix)} $\nu_\mu, \bar{{\nu}}_\mu$",
            )

    # ---------------- NU E ----------------
    if use_nue:
        for prefix in flux_prefixes:
            nue_flux = mceq.get_solution(f"{prefix}nue", mag) + mceq.get_solution(
                f"{prefix}antinue", mag
            )
            ax.plot(
                energies,
                nue_flux,
                label=rf"Fluxo {flux_name.get(prefix, prefix)} $\nu_e, \bar{{\nu}}_e$",
            )

    # ---------------- NU TAU ----------------
    if use_nutau:
        for prefix in flux_prefixes:
            nutau_flux = mceq.get_solution(f"{prefix}nutau", mag) + mceq.get_solution(
                f"{prefix}antinutau", mag
            )
            ax.plot(
                energies,
                nutau_flux,
                label=rf"Fluxo {flux_name.get(prefix, prefix)} $\nu_\tau, \bar{{\nu}}_\tau$",
            )

    ax.set_xlim(1.0, 1e9)
    ax.set_xlabel("Kinetic energy / GeV")

    ax.set_ylim(1e-6, 1.0)
    ax.set_ylabel(r"(E/GeV)$^3$ $\Phi$/(GeV cm$^{-2}$ s$^{-1}$ sr$^{-1}$)")

    fig.text(
        0.95,
        0.5,
        "Generated by AERIS (GAME - UFPel)",
        rotation=90,
        va="center",
        ha="right",
        fontsize=10,
        alpha=0.5,
    )

    ax.legend()
    return fig


st.markdown(
    """
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
""",
    unsafe_allow_html=True,
)

st.markdown(
    """
<style>
@import url("https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&family=Space+Grotesk:wght@400;500;600;700&display=swap");

:root {
    --bg-1: #f6f9ff;
    --bg-2: #eef4ff;
    --card: #ffffff;
    --line: #dbeafe;
    --text-main: #0f172a;
    --text-soft: #334155;
    --accent-1: #2563eb;
    --accent-2: #0284c7;
    --hover: #1d4ed8;
}

.stApp {
    background:
        radial-gradient(circle at 10% 12%, rgba(14, 165, 233, 0.1), transparent 30%),
        radial-gradient(circle at 87% 4%, rgba(37, 99, 235, 0.09), transparent 28%),
        linear-gradient(165deg, var(--bg-2) 0%, var(--bg-1) 40%, #ffffff 100%);
    color: var(--text-main);
    font-family: "Space Grotesk", sans-serif;
}

.block-container {
    max-width: 1500px;
    padding-top: 1.2rem;
}

[data-testid="stSidebar"] {
    background:
        radial-gradient(circle at 18% 6%, rgba(14, 165, 233, 0.12), transparent 30%),
        linear-gradient(180deg, #f8fbff 0%, #eff6ff 100%);
    border-right: 1px solid #dbeafe;
}

[data-testid="stSidebar"] * {
    color: #1e293b !important;
}

[data-testid="stSidebar"] .stImage img {
    border-radius: 14px;
    border: 1px solid #cbd5e1;
    box-shadow: 0 8px 18px rgba(51, 65, 85, 0.12);
}

a {
    color: #1d4ed8 !important;
    text-decoration-thickness: 2px;
}

a:hover {
    color: #1e40af !important;
}

.hero-wrap {
    border: 1px solid #dbeafe;
    background: linear-gradient(145deg, #ffffff, #f8fbff);
    border-radius: 18px;
    padding: 20px 24px;
    box-shadow: 0 10px 24px rgba(30, 41, 59, 0.08);
    text-align: center;
}

.hero-title {
    margin: 0;
    font-size: 2rem;
    letter-spacing: 0.01em;
    color: #0f172a;
}

.hero-subtitle {
    margin: 8px 0 0 0;
    color: #1e293b;
    font-weight: 500;
    line-height: 1.5;
}

.hero-line {
    margin: 6px 0 0 0;
    color: #1e293b;
    font-size: 1.2rem;
    font-weight: 600;
    line-height: 1.45;
}

.hero-line-game {
    font-size: 1.28rem;
    font-weight: 700;
    color: #1d4ed8;
}

.aeris-title {
    text-align: center;
    font-family: "Orbitron", sans-serif;
    font-size: 3rem;
    margin: 0;
    color: #0f172a;
    letter-spacing: 0.12em;
    text-transform: uppercase;
}

.aeris-subtitle {
    text-align: center;
    margin: 6px 0 18px 0;
    font-size: 1rem;
    color: #334155;
    font-weight: 500;
}

hr.aeris-separator {
    border: none;
    height: 2px;
    margin: 18px 0 24px 0;
    background: linear-gradient(90deg, rgba(37, 99, 235, 0), rgba(37, 99, 235, 0.52), rgba(37, 99, 235, 0));
}

div[data-baseweb="tab-list"] {
    background: rgba(239, 246, 255, 0.95);
    border: 1px solid #dbeafe;
    border-radius: 16px;
    padding: 6px;
    margin-bottom: 20px;
}

button[data-baseweb="tab"] {
    border-radius: 12px !important;
    color: #334155 !important;
    font-size: 1.02rem !important;
    font-weight: 600 !important;
    min-height: 48px !important;
    transition: all 0.25s ease !important;
}

button[data-baseweb="tab"][aria-selected="true"] {
    background: linear-gradient(90deg, rgba(14, 165, 233, 0.18), rgba(59, 130, 246, 0.2)) !important;
    color: #0f172a !important;
    box-shadow: inset 0 0 0 1px rgba(96, 165, 250, 0.5);
}

.glass-card {
    border: 1px solid #dbeafe;
    background: linear-gradient(145deg, #ffffff, #f8fbff);
    border-radius: 18px;
    padding: 20px 22px;
    box-shadow: 0 10px 22px rgba(30, 41, 59, 0.08);
}

.section-title {
    font-weight: 600;
    font-size: 1.06rem;
    color: #0f172a;
    margin-bottom: 0.35rem;
}

.section-text {
    font-size: 0.98rem;
    color: #334155;
}

.label-with-help {
    display: flex;
    align-items: center;
    gap: 0.45rem;
    margin-bottom: 0.2rem;
}

.tooltip {
    position: relative;
    display: inline-block;
    cursor: help;
}

.tooltiptext {
    visibility: hidden;
    width: 250px;
    background-color: #1e293b;
    color: #f8fafc;
    text-align: left;
    padding: 9px;
    border: 1px solid rgba(148, 163, 184, 0.7);
    border-radius: 8px;
    position: absolute;
    z-index: 50;
    bottom: 130%;
    left: 50%;
    transform: translateX(-50%);
    opacity: 0;
    transition: opacity 0.22s;
    font-size: 0.82rem;
}

.tooltip:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
}

.tooltip-icon {
    position: relative;
    display: inline-block;
    cursor: pointer;
    background: linear-gradient(150deg, #0284c7, #2563eb);
    color: white;
    font-size: 12px;
    font-weight: bold;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    text-align: center;
    line-height: 18px;
}

.tooltip-icon .tooltiptext {
    visibility: hidden;
    width: 270px;
    background-color: #1e293b;
    color: #fff;
    text-align: left;
    padding: 9px;
    border: 1px solid rgba(148, 163, 184, 0.75);
    border-radius: 8px;
    position: absolute;
    z-index: 50;
    bottom: 130%;
    left: 50%;
    transform: translateX(-50%);
    opacity: 0;
    transition: opacity 0.22s;
    font-size: 0.83rem;
}

.tooltip-icon:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
}

div[data-baseweb="radio"] > div {
    gap: 0.1rem;
}

div[data-baseweb="radio"] label,
div[data-baseweb="checkbox"] label,
div[data-baseweb="select"] * {
    color: var(--text-main) !important;
}

.stTextInput input {
    background-color: #ffffff !important;
    border: 1px solid #bfdbfe !important;
    color: #0f172a !important;
    border-radius: 10px !important;
}

.stButton > button {
    background: linear-gradient(90deg, #3b82f6, #2563eb) !important;
    color: #f8fafc !important;
    border-radius: 999px !important;
    padding: 0.72rem 1rem !important;
    border: 1px solid rgba(37, 99, 235, 0.25) !important;
    font-size: 1rem !important;
    font-weight: 700 !important;
    transition: transform 0.2s ease, box-shadow 0.2s ease !important;
}

.stButton > button:hover {
    transform: translateY(-1px);
    box-shadow: 0 10px 20px rgba(37, 99, 235, 0.28);
    background: linear-gradient(90deg, #2563eb, #1d4ed8) !important;
}

.stDownloadButton > button {
    background: linear-gradient(90deg, #0ea5e9, #0284c7) !important;
    color: white !important;
    border-radius: 999px !important;
    border: 1px solid rgba(14, 165, 233, 0.35) !important;
}

.footer {
    margin-top: 1.5rem;
    padding: 1.4rem;
    border: 1px solid #dbeafe;
    background: linear-gradient(145deg, #ffffff, #f8fbff);
    border-radius: 18px;
    text-align: center;
}

.social-icons {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 18px;
    margin: 0.4rem 0 0.2rem 0;
}

.social-link {
    font-size: 25px;
    color: #334155 !important;
    transition: all 0.2s ease-in-out;
}

.social-link:hover {
    color: #1d4ed8 !important;
    transform: translateY(-2px);
}

.tooltip-footer {
    position: relative;
    display: inline-block;
}

.tooltiptext-footer {
    visibility: hidden;
    width: 155px;
    background-color: #1e293b;
    color: #f8fafc;
    text-align: center;
    padding: 6px;
    border-radius: 6px;
    border: 1px solid rgba(148, 163, 184, 0.75);
    position: absolute;
    z-index: 30;
    bottom: 140%;
    left: 50%;
    margin-left: -77px;
    opacity: 0;
    transition: opacity 0.25s;
    font-size: 0.78rem;
}

.tooltip-footer:hover .tooltiptext-footer {
    visibility: visible;
    opacity: 1;
}

.contact-copy {
    margin-top: 14px;
    color: #334155;
    font-size: 0.95rem;
}

.contact-links {
    margin-top: 0.7rem;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 0.8rem;
}

.contact-pill {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.55rem 0.85rem;
    border-radius: 999px;
    border: 1px solid #bfdbfe;
    background: #f8fbff;
    color: #1e293b !important;
    font-size: 0.93rem;
    text-decoration: none;
    transition: all 0.2s ease;
}

.contact-pill:hover {
    background: #eff6ff;
    border-color: #93c5fd;
    color: #1d4ed8 !important;
    transform: translateY(-1px);
}
</style>
""",
    unsafe_allow_html=True,
)

# ---------------- SIDEBAR ----------------
with st.sidebar:
    st.image("identidadegame.png", use_container_width=True)
    st.markdown("### Other links")
    st.markdown(
        """
- [MCEq Documentation](https://mceq.readthedocs.io/en/latest/index.html)
- [GAME Site](https://wp.ufpel.edu.br/game/)
- [GAME Instagram](https://www.instagram.com/game_ufpel/)
- [GitHub Profile](https://github.com/Tiagoalves-code)
"""
    )

# ---------------- TOP HEADER ----------------
col_logo, col_header = st.columns([1, 4], vertical_alignment="center")
with col_logo:
    st.image("ufpellogo2.png", width=275)

with col_header:
    st.markdown(
        """
<div class="hero-wrap">
    <h1 class="hero-title">Federal University of Pelotas (UFPel)</h1>
    <p class="hero-line">Institute of Physics and Mathematics (IFM)</p>
    <p class="hero-line hero-line-game">High and Medium Energy Group (GAME)</p>
</div>
""",
        unsafe_allow_html=True,
    )

st.markdown('<hr class="aeris-separator">', unsafe_allow_html=True)

tab_home, tab_tools, tab_contact = st.tabs(["Home", "AERIS", "Contact"])

# ---------------- HOME TAB ----------------
with tab_home:
    st.markdown(
        """
<h1 class="aeris-title">AERIS</h1>
<p class="aeris-subtitle"><b>Atmospheric Energy Radiation Interaction Simulator</b></p>
""",
        unsafe_allow_html=True,
    )

    st.markdown(
        """
<div class="glass-card">
    <div style="text-align: justify; font-size: 1.01rem; line-height: 1.65; color: #1e293b;">
        AERIS (Atmospheric Energy Radiation Interaction Simulator) is an interface developed with
        the aim of facilitating the use of the <strong>MCEq (Matrix Cascade Equation)</strong>
        code in studies of atmospheric cascades induced by cosmic rays.
        The tool allows the simulation of secondary particle fluxes in the Earth's atmosphere,
        providing control over hadronic interaction models, primary spectra, and some geometrical
        parameters.<br><br>
        MCEq was originally developed by <strong>Martin Fedynitch</strong> and is a widely used
        tool in the field of High Energy Physics for the study of atmospheric showers and secondary
        particle production. For more details on its implementation and theoretical foundations,
        please refer to the official documentation available at:
        <a href="https://mceq.readthedocs.io/en/latest/index.html" target="_blank">
            MCEq Documentation
        </a>.<br><br>
        This application was built as an interactive interface to explore the features of MCEq,
        aiming to assist students and researchers with simpler simulations of phenomena associated
        with cosmic rays, without the need for programming or running the code locally.<br><br>
        If you have any questions, suggestions, or wish to access the source code of this
        application, please visit the developer's
        <a href="https://github.com/Tiagoalves-code" target="_blank">GitHub</a>.
        To learn more about the research conducted by the High and Medium Energy Group (GAME)
        at UFPel, visit our
        <a href="https://wp.ufpel.edu.br/game/" target="_blank">page</a>.
        Contact information is available at the bottom of the website.
    </div>
</div>
""",
        unsafe_allow_html=True,
    )

# ---------------- TOOLS TAB ----------------
with tab_tools:
    st.markdown(
        """
<div class="glass-card">
    <h3 style="margin-top: 0; margin-bottom: 8px; color: #0f172a; text-align: center;">AERIS</h3>
    <p style="margin-top: 0; color: #334155; text-align: center;">
        Configure the simulation parameters and generate atmospheric particle flux results.
    </p>
</div>
""",
        unsafe_allow_html=True,
    )

    # ================== PARAMETERIZATION ==================
    col1, col2, col3, col4 = st.columns([2.2, 1.2, 1.2, 1.2])

    with col1:
        st.markdown(
            """
        <div class="label-with-help">
            <span class="section-title">Interaction Model</span>
            <span class="tooltip-icon">?
                <span class="tooltiptext">
                    Defines the hadronic interaction model used to simulate cosmic ray collisions with atmospheric nuclei. Different models apply various physics approximations and parameterizations, impacting the secondary particle distributions.
                </span>
            </span>
        </div>
        """,
            unsafe_allow_html=True,
        )

        interaction_model = st.radio(
            "",
            [
                "SIBYLL23E",
                "SIBYLL23D",
                "SIBYLL21",
                "EPOSLHCR",
                "EPOSLHC",
                "QGSJETIII",
                "QGSJETII04",
            ],
        )

    with col2:
        st.markdown(
            """
        <div class="label-with-help">
            <span class="section-title">Primary Model</span>
            <span class="tooltip-icon">?
                <span class="tooltiptext">
                Selects the cosmic-ray primary flux model used in the simulation. Options like H3a, H4a, GST3 end GST4 represent different parameterizations of the cosmic-ray spectrum.
                </span>
            </span>
        </div>
        """,
            unsafe_allow_html=True,
        )

        primary_model = st.radio("", ["H3a", "H4a", "GST3", "GST4"])

    with col2:
        st.markdown(
            """
        <div class="tooltip">
            <span class="section-title">Direction</span>
        </div>
        """,
            unsafe_allow_html=True,
        )

        st.markdown(
            """
        <div class="label-with-help">
            <span class="section-text">Angle</span>
            <span class="tooltip-icon">?
                <span class="tooltiptext">
                Specifies the zenith angle of incoming cosmic rays relative to the vertical.
                An angle of 0° is vertical (straight down), and 90° is horizontal
                (parallel to the ground). Affects the atmospheric depth traveled.
                </span>
            </span>
        </div>
        """,
            unsafe_allow_html=True,
        )
        angle = st.text_input("", placeholder="Angle (°)")

        st.markdown(
            """
        <div class="label-with-help">
            <span class="section-text">Magnitude</span>
            <span class="tooltip-icon">?
                <span class="tooltiptext">
                Represents the energy power with which the flux is multiplied,
                highlighting features of the spectrum.
                </span>
            </span>
        </div>
        """,
            unsafe_allow_html=True,
        )
        magnitude = st.text_input("", placeholder="Magnitude")

    with col3:
        st.markdown(
            """
        <div class="label-with-help">
            <span class="section-title">Particles</span>
            <span class="tooltip-icon">?
                <span class="tooltiptext">
                Selects the types of secondary particles to track in the simulation. Options typically include muons and different types of neutrinos, which are produced during cosmic ray interactions.
                </span>
            </span>
        </div>
        """,
            unsafe_allow_html=True,
        )

        muons = st.checkbox("Muons")
        muon_neutrinos = st.checkbox("Muon Neutrinos")
        electron_neutrinos = st.checkbox("Electron Neutrinos")
        tau_neutrinos = st.checkbox("Tau Neutrinos")

    with col4:
        st.markdown(
            """
        <div class="label-with-help">
            <span class="section-title">Interaction Model</span>
            <span class="tooltip-icon">?
                <span class="tooltiptext">
                Determines the component of atmospheric particle flux to consider. Conventional flux comes from pion and kaon decays, while prompt flux originates from heavier charm meson decays. The total flux includes both contributions.
                </span>
            </span>
        </div>
        """,
            unsafe_allow_html=True,
        )

        conventional = st.checkbox("Conventional")
        prompt = st.checkbox("Prompt")
        total = st.checkbox("Total")

    st.markdown("<br>", unsafe_allow_html=True)
    simulate = st.button("Simulate", use_container_width=True)

    flux_prefixes = []
    if prompt:
        flux_prefixes.append("pr_")
    if conventional:
        flux_prefixes.append("conv_")
    if total:
        flux_prefixes.append("total_")

    if simulate:
        if angle.strip() == "":
            st.error("Please enter a value for the angle (θ).")
        elif magnitude.strip() == "":
            st.error("Please enter a value for the magnitude.")
        else:
            try:
                theta_val = float(angle)
            except ValueError:
                st.error("Angle must be a valid number.")
                theta_val = None

            try:
                mag = int(magnitude)
            except ValueError:
                st.error("Magnitude must be an integer.")
                mag = None

            if theta_val is not None and theta_val < 0:
                st.error("Please enter a valid value for the angle (θ).")
                theta_val = None

            if mag is not None and mag >= 4:
                st.error(
                    "Please select a magnitude value less than 4. "
                    "The default value that provides the best visualization is 3."
                )
                mag = None
            elif mag is not None and mag <= 0:
                st.error("Please enter a valid value for the magnitude.")
                mag = None

            if theta_val is not None and mag is not None:
                st.info("Running MCEq simulation...")
                try:
                    fig = run_mceq(
                        interaction_model=interaction_model,
                        primary_model_name=primary_model,
                        theta_deg=theta_val,
                        mag=mag,
                        use_muons=muons,
                        use_numu=muon_neutrinos,
                        use_nue=electron_neutrinos,
                        use_nutau=tau_neutrinos,
                        flux_prefixes=flux_prefixes,
                    )
                except Exception as exc:
                    st.error(f"Simulation error: {exc}")
                else:
                    st.success("Simulation finished successfully!")
                    st.session_state.last_fig = fig

                    buf = io.BytesIO()
                    fig.savefig(buf, format="png", bbox_inches="tight")
                    buf.seek(0)
                    st.session_state.last_png = buf.getvalue()

    # ================== GRAPH AREA ==================
    left_spacer, center_area, right_spacer = st.columns([1.2, 1.6, 1.2])
    with center_area:
        st.markdown(
            """
        <h3 style="text-align: center; color: #0f172a;">
        Simulation Output
        </h3>
    """,
            unsafe_allow_html=True,
        )

        if st.session_state.last_fig is not None:
            st.pyplot(st.session_state.last_fig, use_container_width=False)

            _, download_col, _ = st.columns([1, 1, 1])
            with download_col:
                st.download_button(
                    label="Download",
                    data=st.session_state.last_png,
                    file_name="mceq_result.png",
                    mime="image/png",
                    use_container_width=True,
                )
        else:
            st.image(
                "https://dummyimage.com/900x400/e2e8f0/1e293b&text=Waiting+for+Simulation",
                caption="Results will appear here",
                use_container_width=True,
            )

# ---------------- CONTACT TAB ----------------
with tab_contact:
    st.markdown(
        """
<div class="footer">
    <h3 style="margin: 0 0 8px 0; color: #0f172a;">Contact and Resources</h3>
    <div class="contact-links">
        <a class="contact-pill" href="https://mceq.readthedocs.io/en/latest/index.html" target="_blank" title="MCEq Documentation">
            <i class="fas fa-file-alt"></i> MCEq Documentation
        </a>
        <a class="contact-pill" href="https://wp.ufpel.edu.br/game/" target="_blank" title="GAME Site">
            <i class="fas fa-globe"></i> GAME Site
        </a>
        <a class="contact-pill" href="https://www.instagram.com/game_ufpel/" target="_blank" title="GAME Instagram">
            <i class="fab fa-instagram"></i> GAME Instagram
        </a>
        <a class="contact-pill" href="mailto:tiagoalves304@gmail.com" title="Developer's Email">
            <i class="fas fa-envelope"></i> Developer's Email
        </a>
        <a class="contact-pill" href="https://www.linkedin.com/in/tiago-alves-pereira-90649a186/" target="_blank" title="Developer's LinkedIn">
            <i class="fab fa-linkedin"></i> Developer's LinkedIn
        </a>
        <a class="contact-pill" href="https://github.com/Tiagoalves-code" target="_blank" title="GitHub Profile">
            <i class="fab fa-github"></i> GitHub Profile
        </a>
    </div>
    <p class="contact-copy">
        AERIS | High and Medium Energy Group (GAME) - UFPel
    </p>
</div>
""",
        unsafe_allow_html=True,
    )
